CC=g++

CFLAGS=-c -Wall -Wextra

all: Disassembler

Disassembler: main.o Disassembler.o Reading_File.o Log_File.o
	$(CC) main.o Disassembler.o Reading_File.o Log_File.o -o Disassembler
	rm -rf *.o
	./Disassembler
	rm Disassembler

main.o: main.cpp
	$(CC) $(CFLAGS) main.cpp

Disassembler.o: Disassembler.cpp
	$(CC) $(CFLAGS) Disassembler.cpp

Reading_File.o: ../Reading_File.cpp
	$(CC) $(CFLAGS) ../Reading_File.cpp

Log_File.o: ../Log_File.cpp
	$(CC) $(CFLAGS) ../Log_File.cpp